/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestaoveiculos_project.mavenproject1;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Veronica
 */
public class FormCadastroCarga extends javax.swing.JFrame {

    private static Carga carga = new Carga();
    BDVeiculos bdVeiculos = BDVeiculos.getInstance();

    /**
     * Creates new form FormCadastroCarga
     */
    public FormCadastroCarga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new java.awt.Button();
        labelPistoes = new javax.swing.JLabel();
        btnNovo = new java.awt.Button();
        labelPotenc = new javax.swing.JLabel();
        btnLimpar = new java.awt.Button();
        fieldPlaca = new javax.swing.JTextField();
        btnCadastrar = new java.awt.Button();
        labelPlaca = new javax.swing.JLabel();
        fieldMarca = new javax.swing.JTextField();
        labelMarca = new javax.swing.JLabel();
        fieldModelo = new javax.swing.JTextField();
        labelModelo = new javax.swing.JLabel();
        fieldCor = new javax.swing.JTextField();
        labelCor = new javax.swing.JLabel();
        fieldRodas = new javax.swing.JTextField();
        labelRodas = new javax.swing.JLabel();
        fieldVeloc = new javax.swing.JTextField();
        fieldPistoes = new javax.swing.JTextField();
        fieldPotenc = new javax.swing.JTextField();
        labelVeloc = new javax.swing.JLabel();
        labelCargaMax = new javax.swing.JLabel();
        labelTara = new javax.swing.JLabel();
        fieldCargaMax = new javax.swing.JTextField();
        fieldTara = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Carga");

        btnSair.setBackground(new java.awt.Color(220, 220, 220));
        btnSair.setLabel("Sair");
        btnSair.setName(""); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        labelPistoes.setText("Quantidade Pistões:");

        btnNovo.setBackground(new java.awt.Color(220, 220, 220));
        btnNovo.setLabel("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        labelPotenc.setText("Potência:");

        btnLimpar.setBackground(new java.awt.Color(220, 220, 220));
        btnLimpar.setLabel("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        fieldPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPlacaActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(220, 220, 220));
        btnCadastrar.setLabel("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        labelPlaca.setText("Placa:");
        labelPlaca.setToolTipText("");
        labelPlaca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelMarca.setText("Marca:");

        labelModelo.setText("Modelo:");

        labelCor.setText("Cor:");

        labelRodas.setText("Quantidade Rodas:");

        labelVeloc.setText("Velocidade Max.:");

        labelCargaMax.setText("Carga Max:");

        labelTara.setText("Tara:");

        fieldCargaMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCargaMaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelPotenc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPistoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelVeloc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelRodas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fieldPistoes, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldVeloc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldRodas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldCor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldModelo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldMarca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldPlaca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldPotenc, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelCargaMax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTara, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 55, Short.MAX_VALUE)
                                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldTara, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(fieldCargaMax))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTara)
                    .addComponent(fieldTara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCargaMax)
                    .addComponent(fieldCargaMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPlaca)
                    .addComponent(fieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMarca)
                    .addComponent(fieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelModelo)
                    .addComponent(fieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCor)
                    .addComponent(fieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRodas)
                    .addComponent(fieldRodas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelVeloc)
                    .addComponent(fieldVeloc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPistoes)
                    .addComponent(fieldPistoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPotenc)
                    .addComponent(fieldPotenc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void fieldPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPlacaActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
       fieldPlaca.setText("");
        fieldMarca.setText(""); 
        fieldModelo.setText(""); 
        fieldCor.setText(""); 
        fieldRodas.setText(""); 
        fieldVeloc.setText(""); 
        fieldPistoes.setText(""); 
        fieldPotenc.setText("");
        fieldCargaMax.setText("");
        fieldTara.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void fieldCargaMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCargaMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCargaMaxActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            String placa = fieldPlaca.getText().trim();
            if (placaExiste(placa)) {
                JOptionPane.showMessageDialog(this, "Placa já cadastrada!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            carga = new Carga();
            carga.setPlaca(placa);
            carga.setMarca(fieldMarca.getText().trim());
            carga.setModelo(fieldModelo.getText().trim());
            carga.setCor(fieldCor.getText().trim());

            try {
                float vel = Float.parseFloat(fieldVeloc.getText().trim());
                if (vel < 80 || vel > 110) {
                    carga.setVelocMax(90); // padrão para carga
                    throw new VelocException();
                } else {
                    carga.setVelocMax(vel);
                }
            } catch (VelocException ve) {
                JOptionPane.showMessageDialog(this, "Velocidade fora do limite. Definida como 90 km/h.\nClasse: " + ve.getClass().getName());
            }

            carga.setQtdRodas(Integer.parseInt(fieldRodas.getText().trim()));
            carga.setTara(Integer.parseInt(fieldTara.getText().trim()));
            carga.setCargaMax(Integer.parseInt(fieldCargaMax.getText().trim()));
            carga.getMotor().setQtdPist(Integer.parseInt(fieldPistoes.getText().trim()));
            carga.getMotor().setPotencia(Integer.parseInt(fieldPotenc.getText().trim()));

            carga.calcVel(carga.getVelocMax());
            carga.calcular();

            bdVeiculos.getListaCarga().add(carga);

            JOptionPane.showMessageDialog(this, "Veículo de carga cadastrado com sucesso!");

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Campos numéricos inválidos ou em branco.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro não tratado: " + ex.getMessage() + Arrays.toString(ex.getStackTrace()), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
       fieldPlaca.setText("");
        fieldMarca.setText(""); 
        fieldModelo.setText(""); 
        fieldCor.setText(""); 
        fieldRodas.setText(""); 
        fieldVeloc.setText(""); 
        fieldPistoes.setText(""); 
        fieldPotenc.setText("");
        fieldCargaMax.setText("");
        fieldTara.setText("");
    }//GEN-LAST:event_btnNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormCadastroCarga().setVisible(true);
        });
    }

    public boolean placaExiste(String placa) {
        return bdVeiculos.getListaPasseio().stream().anyMatch(e -> e.getPlaca().equalsIgnoreCase(placa))
                || bdVeiculos.getListaCarga().stream().anyMatch(e -> e.getPlaca().equalsIgnoreCase(placa));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnCadastrar;
    private java.awt.Button btnLimpar;
    private java.awt.Button btnNovo;
    private java.awt.Button btnSair;
    private javax.swing.JTextField fieldCargaMax;
    private javax.swing.JTextField fieldCor;
    private javax.swing.JTextField fieldMarca;
    private javax.swing.JTextField fieldModelo;
    private javax.swing.JTextField fieldPistoes;
    private javax.swing.JTextField fieldPlaca;
    private javax.swing.JTextField fieldPotenc;
    private javax.swing.JTextField fieldRodas;
    private javax.swing.JTextField fieldTara;
    private javax.swing.JTextField fieldVeloc;
    private javax.swing.JLabel labelCargaMax;
    private javax.swing.JLabel labelCor;
    private javax.swing.JLabel labelMarca;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelPistoes;
    private javax.swing.JLabel labelPlaca;
    private javax.swing.JLabel labelPotenc;
    private javax.swing.JLabel labelRodas;
    private javax.swing.JLabel labelTara;
    private javax.swing.JLabel labelVeloc;
    // End of variables declaration//GEN-END:variables
}
